#!/usr/bin/env bash
#
# fork/build.sh — build the integration branch and run it on this machine.
#
# The build lives in its own persistent checkout ($FORK_WORK_ROOT/build) so
# node_modules survives between builds and nothing here disturbs the checkout
# you work in.
#
# Commands:
#   fork/build.sh build        checkout panrafal, install deps, build server+CLI
#   fork/build.sh install      build, then install the `paseo-fork` launcher
#   fork/build.sh start        start the fork daemon (side-by-side)
#   fork/build.sh stop         stop the fork daemon
#   fork/build.sh restart      build + install + restart the fork daemon
#   fork/build.sh status       where things are and what is running
#   fork/build.sh desktop      build the Linux desktop app in the build checkout
#
# Flags:
#   --sync        run fork/sync.sh first
#   --clean       wipe node_modules and dist before building
#   --skip-check  skip typecheck and lint
#
# On this machine the system daemon (port 6767, /usr/lib/node_modules, systemd
# `paseo.service`) cannot be replaced: /usr and /etc are read-only and there is
# no root. The fork therefore runs as a SECOND daemon with its own PASEO_HOME
# and port. See fork/README.md.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=fork/config.sh
. "$HERE/config.sh"

cmd="build"
do_sync=0 do_clean=0 skip_check=0
for arg in "$@"; do
  case "$arg" in
    build | install | start | stop | restart | status | desktop) cmd="$arg" ;;
    --sync) do_sync=1 ;;
    --clean) do_clean=1 ;;
    --skip-check) skip_check=1 ;;
    -h | --help)
      sed -n '3,26p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) die "unknown argument: $arg" ;;
  esac
done

require_repo
CLI_ENTRY="$BUILD_DIR/packages/cli/dist/index.js"
LAUNCHER="$FORK_BIN_DIR/paseo-fork"
PID_FILE="$WORK_ROOT/daemon.pid"
LOG_FILE="$WORK_ROOT/daemon.log"

fork_cli() {
  PASEO_HOME="$FORK_PASEO_HOME" node "$CLI_ENTRY" "$@"
}

# ------------------------------------------------------------- checkout ----

prepare_checkout() {
  git rev-parse --verify -q "$TARGET^{commit}" >/dev/null ||
    die "branch '$TARGET' does not exist — run fork/sync.sh first"
  local sha
  sha="$(git rev-parse "$TARGET")"

  mkdir -p "$WORK_ROOT"
  if [ ! -e "$BUILD_DIR/.git" ]; then
    rm -rf "$BUILD_DIR"
    git worktree prune
    say "Creating build checkout at $BUILD_DIR"
    git worktree add --detach "$BUILD_DIR" "$sha" >/dev/null
  else
    # Detached, so sync.sh can force-move `panrafal` underneath us freely.
    git -C "$BUILD_DIR" checkout --detach --force "$sha" >/dev/null 2>&1
    git -C "$BUILD_DIR" clean -fdq -e node_modules -e '**/node_modules' -e '**/dist'
  fi
  say "Build checkout at $(git -C "$BUILD_DIR" log -1 --format='%h %s')"
}

# ---------------------------------------------------------------- build ----

do_build() {
  prepare_checkout

  if [ "$do_clean" -eq 1 ]; then
    say "Cleaning node_modules and dist"
    (cd "$BUILD_DIR" && find . -maxdepth 3 -name node_modules -type d -prune -exec rm -rf {} + &&
      find packages -maxdepth 2 -name dist -type d -prune -exec rm -rf {} + 2>/dev/null || true)
  fi

  say "Installing dependencies"
  (cd "$BUILD_DIR" && npm install --no-audit --no-fund)

  say "Building server, CLI and bundled web UI"
  (cd "$BUILD_DIR" && npm run build:server && npm run build:daemon-web-ui)

  if [ "$skip_check" -eq 0 ]; then
    say "Typecheck and lint"
    (cd "$BUILD_DIR" && npm run typecheck:server && npm run lint)
  fi

  [ -f "$CLI_ENTRY" ] || die "build finished but $CLI_ENTRY is missing"
  say "Built $TARGET -> $(fork_cli --version)"
}

# -------------------------------------------------------------- install ----

do_install() {
  mkdir -p "$FORK_BIN_DIR" "$FORK_PASEO_HOME"
  cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by fork/build.sh. The Paseo fork build, side by side with the
# system install. Rebuild with: fork/build.sh restart
export PASEO_HOME="\${PASEO_HOME:-$FORK_PASEO_HOME}"
export PASEO_LISTEN="\${PASEO_LISTEN:-$FORK_PASEO_LISTEN}"
export PASEO_WEB_UI_ENABLED="\${PASEO_WEB_UI_ENABLED:-true}"
exec node "$CLI_ENTRY" "\$@"
EOF
  chmod +x "$LAUNCHER"
  say "Installed launcher: $LAUNCHER"
  case ":$PATH:" in
    *":$FORK_BIN_DIR:"*) ;;
    *) warn "$FORK_BIN_DIR is not on PATH — add it to use \`paseo-fork\`" ;;
  esac
}

# --------------------------------------------------------------- daemon ----

fork_daemon_pid() {
  [ -f "$PID_FILE" ] || return 1
  local pid
  pid="$(cat "$PID_FILE")"
  kill -0 "$pid" 2>/dev/null || return 1
  echo "$pid"
}

do_start() {
  if pid="$(fork_daemon_pid)"; then
    say "Fork daemon already running (pid $pid) on $FORK_PASEO_LISTEN"
    return
  fi
  mkdir -p "$FORK_PASEO_HOME"
  say "Starting fork daemon on $FORK_PASEO_LISTEN (home: $FORK_PASEO_HOME)"
  setsid nohup node "$CLI_ENTRY" daemon start --foreground \
    --home "$FORK_PASEO_HOME" --listen "$FORK_PASEO_LISTEN" --web-ui \
    >>"$LOG_FILE" 2>&1 </dev/null &
  echo $! >"$PID_FILE"
  sleep 2
  if pid="$(fork_daemon_pid)"; then
    say "Fork daemon running (pid $pid). Logs: $LOG_FILE"
  else
    die "fork daemon exited immediately — see $LOG_FILE"
  fi
}

do_stop() {
  if pid="$(fork_daemon_pid)"; then
    say "Stopping fork daemon (pid $pid)"
    kill "$pid" 2>/dev/null || true
    for _ in $(seq 1 20); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.5
    done
    kill -9 "$pid" 2>/dev/null || true
  else
    say "Fork daemon not running"
  fi
  rm -f "$PID_FILE"
}

do_status() {
  echo "target branch     $TARGET ($(git rev-parse --short "$TARGET" 2>/dev/null || echo '-'))"
  echo "build checkout    $BUILD_DIR ($(git -C "$BUILD_DIR" rev-parse --short HEAD 2>/dev/null || echo 'not created'))"
  echo "built version     $([ -f "$CLI_ENTRY" ] && fork_cli --version 2>/dev/null || echo 'not built')"
  echo "launcher          $([ -x "$LAUNCHER" ] && echo "$LAUNCHER" || echo 'not installed')"
  echo "fork PASEO_HOME   $FORK_PASEO_HOME"
  echo "fork listen       $FORK_PASEO_LISTEN"
  echo "fork daemon       $(fork_daemon_pid >/dev/null && echo "running (pid $(fork_daemon_pid))" || echo 'stopped')"
  echo "system daemon     $(command -v paseo >/dev/null && paseo --version 2>/dev/null || echo '-') at /usr/lib/node_modules (read-only, not replaceable)"
}

do_desktop() {
  say "Building the Linux desktop app in $BUILD_DIR"
  (cd "$BUILD_DIR" && npm run build:desktop)
  say "Artifacts: $BUILD_DIR/packages/desktop/release"
}

# ------------------------------------------------------------------ run ----

[ "$do_sync" -eq 0 ] || "$HERE/sync.sh"

case "$cmd" in
  build) do_build ;;
  install)
    do_build
    do_install
    ;;
  start) do_start ;;
  stop) do_stop ;;
  restart)
    do_build
    do_install
    do_stop
    do_start
    ;;
  status) do_status ;;
  desktop)
    prepare_checkout
    do_desktop
    ;;
esac
